[2017-06-19 11:34:19] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:19] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1285 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:19] core.ERROR: Prevented access to /admin/ because there is no user in the session! {"server":{"REDIRECT_APPLICATION_ENV":"development","REDIRECT_STATUS":"200","APPLICATION_ENV":"development","HTTP_HOST":"atitesting-dev.com","HTTP_CONNECTION":"keep-alive","HTTP_UPGRADE_INSECURE_REQUESTS":"1","HTTP_USER_AGENT":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36","HTTP_ACCEPT":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","HTTP_REFERER":"http://atitesting-dev.com/install/","HTTP_ACCEPT_ENCODING":"gzip, deflate, sdch","HTTP_ACCEPT_LANGUAGE":"en-US,en;q=0.8","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","SERVER_SIGNATURE":"<address>Apache/2.4.10 (Ubuntu) Server at atitesting-dev.com Port 80</address>\n","SERVER_SOFTWARE":"Apache/2.4.10 (Ubuntu)","SERVER_NAME":"atitesting-dev.com","SERVER_ADDR":"127.0.0.1","SERVER_PORT":"80","REMOTE_ADDR":"127.0.0.1","DOCUMENT_ROOT":"/var/www/html/atitesting/atitesting","REQUEST_SCHEME":"http","CONTEXT_PREFIX":"","CONTEXT_DOCUMENT_ROOT":"/var/www/html/atitesting/atitesting","SERVER_ADMIN":"[no address given]","SCRIPT_FILENAME":"/var/www/html/atitesting/atitesting/index.php","REMOTE_PORT":"48524","REDIRECT_URL":"/admin/","GATEWAY_INTERFACE":"CGI/1.1","SERVER_PROTOCOL":"HTTP/1.1","REQUEST_METHOD":"GET","QUERY_STRING":"","REQUEST_URI":"/admin/","SCRIPT_NAME":"/index.php","PHP_SELF":"/index.php","REQUEST_TIME_FLOAT":1497864859.513,"REQUEST_TIME":1497864859,"TMPDIR":"/var/www/html/atitesting/atitesting/website/var/cache","TEMP":"/var/www/html/atitesting/atitesting/website/var/cache","TMP":"/var/www/html/atitesting/atitesting/website/var/cache","windir":"/var/www/html/atitesting/atitesting/website/var/cache","SystemRoot":"/var/www/html/atitesting/atitesting/website/var/cache"},"get":[],"post":[],"session":null,"cookie":[],"origin":"Pimcore\\Controller\\Action\\Admin->init() on line 130","memory":"  3 MB"} []
[2017-06-19 11:34:19] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:19] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1286 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:25] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:25] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1287 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:25] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1288 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1289 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1290 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:26] core.INFO: Cannot find perspectives configuration, should be located at: /var/www/html/atitesting/atitesting/website/var/config/perspectives.php {"origin":"Pimcore\\Config::getPerspectivesConfig() on line 352","memory":"  4 MB"} []
[2017-06-19 11:34:26] core.WARNING: exception 'Exception' with message 'No 'ffmpeg' executable found, please install the application or add it to the PATH (in system settings or to your PATH environment variable' in /var/www/html/atitesting/atitesting/pimcore/lib/Pimcore/Tool/Console.php:135 Stack trace: #0 /var/www/html/atitesting/atitesting/pimcore/lib/Pimcore/Video/Adapter/Ffmpeg.php(67): Pimcore\Tool\Console::getExecutable('ffmpeg', true) #1 /var/www/html/atitesting/atitesting/pimcore/lib/Pimcore/Video/Adapter/Ffmpeg.php(49): Pimcore\Video\Adapter\Ffmpeg::getFfmpegCli() #2 /var/www/html/atitesting/atitesting/pimcore/lib/Pimcore/Video.php(74): Pimcore\Video\Adapter\Ffmpeg->isAvailable() #3 /var/www/html/atitesting/atitesting/pimcore/lib/Pimcore/Video.php(55): Pimcore\Video::getDefaultAdapter() #4 /var/www/html/atitesting/atitesting/pimcore/modules/admin/views/scripts/index/index6.php(585): Pimcore\Video::isAvailable() #5 /var/www/html/atitesting/atitesting/vendor/zendframework/zendframework1/library/Zend/View.php(157): include('/var/www/html/a...') #6 /var/www/html/atitesting/atitesting/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php(888): Zend_View->_run('/var/www/html/a...') #7 /var/www/html/atitesting/atitesting/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render('index/index6.ph...') #8 /var/www/html/atitesting/atitesting/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/index6.ph...', NULL) #9 /var/www/html/atitesting/atitesting/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render() #10 /var/www/html/atitesting/atitesting/pimcore/lib/Pimcore/Controller/Action/Helper/ViewRenderer.php(42): Zend_Controller_Action_Helper_ViewRenderer->postDispatch() #11 /var/www/html/atitesting/atitesting/vendor/zendframework/zendframework1/library/Zend/Controller/Action/HelperBroker.php(277): Pimcore\Controller\Action\Helper\ViewRenderer->postDispatch() #12 /var/www/html/atitesting/atitesting/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch() #13 /var/www/html/atitesting/atitesting/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('index6Action') #14 /var/www/html/atitesting/atitesting/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #15 /var/www/html/atitesting/atitesting/pimcore/lib/Pimcore.php(159): Zend_Controller_Front->dispatch(NULL, NULL) #16 /var/www/html/atitesting/atitesting/pimcore/lib/Pimcore.php(125): Pimcore::runDispatcher(Object(Zend_Controller_Front), false, NULL, NULL) #17 /var/www/html/atitesting/atitesting/index.php(18): Pimcore::run() #18 {main} {"origin":"Pimcore\\Video\\Adapter\\Ffmpeg->isAvailable() on line 55","memory":"  4 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Key pimcore_minimized_script_path doesn't exist in cache {"origin":"Pimcore\\Cache::load() on line 299","memory":"  4 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1291 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1292 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Added pimcore_minimized_script_path to cache {"origin":"Pimcore\\Cache::storeToCache() on line 511","memory":"  4 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1295 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1297 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1294 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1293 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1296 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Key pimcore_system_supported_locales_en doesn't exist in cache {"origin":"Pimcore\\Cache::load() on line 299","memory":"  3 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1298 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1299 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1300 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1302 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1301 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Key pimcore_translations_admin_data doesn't exist in cache {"origin":"Pimcore\\Cache::load() on line 299","memory":"  4 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1303 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:26] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1304 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:27] core.DEBUG: Added pimcore_translations_admin_data to cache {"origin":"Pimcore\\Cache::storeToCache() on line 511","memory":"  4 MB"} []
[2017-06-19 11:34:58] core.DEBUG: Added pimcore_system_supported_locales_en to cache {"origin":"Pimcore\\Cache::storeToCache() on line 511","memory":"  4 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1305 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1306 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1307 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1308 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1309 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1310 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1311 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1312 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Successfully got data for key pimcore_system_supported_locales_en from cache {"origin":"Pimcore\\Cache::load() on line 297","memory":"  4 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1313 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:34:59] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1314 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1315 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1316 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Key pimcore_document_1 doesn't exist in cache {"origin":"Pimcore\\Cache::load() on line 299","memory":"  3 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1317 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1318 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1319 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1320 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1321 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Added pimcore_document_1 to cache {"origin":"Pimcore\\Cache::storeToCache() on line 511","memory":"  4 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Key pimcore_object_1 doesn't exist in cache {"origin":"Pimcore\\Cache::load() on line 299","memory":"  3 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1322 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:35:00] core.INFO: Cannot find perspectives configuration, should be located at: /var/www/html/atitesting/atitesting/website/var/config/perspectives.php {"origin":"Pimcore\\Config::getPerspectivesConfig() on line 352","memory":"  3 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Key pimcore_asset_1 doesn't exist in cache {"origin":"Pimcore\\Cache::load() on line 299","memory":"  4 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Added pimcore_object_1 to cache {"origin":"Pimcore\\Cache::storeToCache() on line 511","memory":"  4 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Added pimcore_asset_1 to cache {"origin":"Pimcore\\Cache::storeToCache() on line 511","memory":"  4 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1323 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1324 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1325 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:35:00] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1326 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:35:01] core.DEBUG: Initialize dedicated MySQL connection for the cache adapter {"origin":"Pimcore\\Cache\\Backend\\MysqlTable->getDb() on line 50","memory":"  1 MB"} []
[2017-06-19 11:35:01] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1327 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  2 MB"} []
[2017-06-19 11:35:01] core.DEBUG: Zend_Db_Adapter_Pdo_Mysql: Successfully established connection to MySQL-Server, Process-ID: 1328 {"origin":"Pimcore\\Db::getConnection() on line 109","memory":"  3 MB"} []
[2017-06-19 11:35:01] core.DEBUG: Successfully got data for key pimcore_object_1 from cache {"origin":"Pimcore\\Cache::load() on line 297","memory":"  4 MB"} []
